// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRainbow = "rainbow"

// Rainbow mapped from table <rainbow>
type Rainbow struct {
	TimeInZero int32  `gorm:"column:timeInZero;type:INTEGER;primaryKey" json:"timeInZero"`
	Value      string `gorm:"column:value;type:TEXT;not null" json:"value"`
	IsUpload   int32  `gorm:"column:isUpload;type:INTEGER;not null" json:"isUpload"`
}

// TableName Rainbow's table name
func (*Rainbow) TableName() string {
	return TableNameRainbow
}
