// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSportSummary = "sport_summary"

// SportSummary mapped from table <sport_summary>
type SportSummary struct {
	Category      string `gorm:"column:category;type:TEXT;primaryKey" json:"category"`
	Dimen         string `gorm:"column:dimen;type:TEXT;not null" json:"dimen"`
	TimeIn0TZ     int64  `gorm:"column:timeIn0TZ;type:INTEGER;not null" json:"timeIn0TZ"`
	ZoneOffsetSec int64  `gorm:"column:zoneOffsetSec;type:INTEGER;not null" json:"zoneOffsetSec"`
	Summary       string `gorm:"column:summary;type:TEXT;not null" json:"summary"`
}

// TableName SportSummary's table name
func (*SportSummary) TableName() string {
	return TableNameSportSummary
}
