// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVitalityRecord = "vitality_record"

// VitalityRecord mapped from table <vitality_record>
type VitalityRecord struct {
	Key             string  `gorm:"column:key;type:TEXT;primaryKey" json:"key"`
	Sid             string  `gorm:"column:sid;type:TEXT;not null" json:"sid"`
	Time            int64   `gorm:"column:time;type:INTEGER;primaryKey" json:"time"`
	ZoneOffsetInSec int64   `gorm:"column:zoneOffsetInSec;type:INTEGER;not null" json:"zoneOffsetInSec"`
	ZoneName        *string `gorm:"column:zoneName;type:TEXT" json:"zoneName"`
	TimeIn0Tz       int64   `gorm:"column:timeIn0Tz;type:INTEGER;not null" json:"timeIn0Tz"`
	IsUpload        int64   `gorm:"column:isUpload;type:INTEGER;not null" json:"isUpload"`
	IsDeleted       int64   `gorm:"column:isDeleted;type:INTEGER;not null" json:"isDeleted"`
	Value           *string `gorm:"column:value;type:TEXT" json:"value"`
}

// TableName VitalityRecord's table name
func (*VitalityRecord) TableName() string {
	return TableNameVitalityRecord
}
