// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q            = new(Query)
	DailyReport  *dailyReport
	Rainbow      *rainbow
	SportSummary *sportSummary
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	DailyReport = &Q.DailyReport
	Rainbow = &Q.Rainbow
	SportSummary = &Q.SportSummary
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:           db,
		DailyReport:  newDailyReport(db, opts...),
		Rainbow:      newRainbow(db, opts...),
		SportSummary: newSportSummary(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	DailyReport  dailyReport
	Rainbow      rainbow
	SportSummary sportSummary
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		DailyReport:  q.DailyReport.clone(db),
		Rainbow:      q.Rainbow.clone(db),
		SportSummary: q.SportSummary.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		DailyReport:  q.DailyReport.replaceDB(db),
		Rainbow:      q.Rainbow.replaceDB(db),
		SportSummary: q.SportSummary.replaceDB(db),
	}
}

type queryCtx struct {
	DailyReport  IDailyReportDo
	Rainbow      IRainbowDo
	SportSummary ISportSummaryDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		DailyReport:  q.DailyReport.WithContext(ctx),
		Rainbow:      q.Rainbow.WithContext(ctx),
		SportSummary: q.SportSummary.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
